language: python

python:
  - "3.7-dev"

sudo: required

services:
  - docker

install:
  - pip install flake8 pipenv salt-pepper
  - pipenv install --deploy

script:
  - pipenv run lint
  - sh docker/build.sh
  - pepper "glimglam.gserv.me" state.apply socker/hacktoberbot -u $SALTAPI_URL -a $SALTAPI_EAUTH --username SALTAPI_USER --password SALTAPI_PASS &> /dev/null
